version: "3.1"

services:
  mysql:
    image: mysql:latest
    container_name: baekjoon-mysql
    ports:
      - "3306:3306"

    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
      MYSQL_DATABASE: baekjoon
      MYSQL_USER: bamboo
      MYSQL_PASSWORD_FILE: /run/secrets/db_bamboo_password

    command:
      - --character-set-server=utf8
      - --collation-server=utf8_unicode_ci

    volumes:
      - ./baekjoon-mysql-volume:/var/lib/mysql

    restart: always

    secrets:
      - db_root_password
      - db_bamboo_password

secrets:
  db_root_password:
    file: ./secrets/db_root_password.txt
  db_bamboo_password:
    file: ./secrets/db_bamboo_password.txt