spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:mysql://localhost:3306/baekjoon
    username: bamboo
    password: bamboo
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
#        show_sql: true
        format_sql: true
#        use-new-id-generator-mappings: false
    database-platform: org.hibernate.dialect.MySQL8Dialect

logging:
  level:
    org.hibernate.SQL: debug
    com.bamboo: debug
#    org.hibernate.type: trace

jwt:
  header: Authorization
  secret: ${jwt-secret}
  token-validity-in-seconds: ${jwt-token-validity-in-seconds}

server:
  error:
    include-message: always